name: SQL for GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    - uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './GitHubActionsProject/GitHubActionsProject.sqlproj'
        action: 'DeployReport'
        arguments: /DeployReportPath=deploy.sql
    - uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './GitHubActionsProject/bin/Debug/GitHubActionsProject.dacpac'
        action: 'Publish'
        build-arguments: '-c Release' # Optional build options passed to dotnet build
    # Azure logout 
    - name: logout
      run: |
         az logout
