name: SQL for GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: windows-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 
    # Find msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      # create dacpac using MSBUILD
    - name: Build Database project
      run: |
          msbuild.exe ./GitHubActionsProject/bin/Debug/GitHubActionsProject.dacpac /p:Configuration=Release
      # Publish artifact
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: SQLDB
        path: ${{ github.workspace }}/bin/Release/ 
    - uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './GitHubActionsProject/bin/Debug/GitHubActionsProject.dacpac'
        action: 'Publish'
    # Azure logout 
    - name: logout
      run: |
         az logout
